org.gradle.jvmargs=-Xmx2G
modName=MoogsMissingVillages
minecraftVersion=1.20
modVersion=2.1.2
modId=mmv
modDescription=This is a mod which adds in the missing jungle and swamp villages in a vanilla friendly way and style
modHomepage=https://www.curseforge.com/minecraft/mc-mods/mmv-moogs-missing-villages
modSources=https://github.com/FinnSetchell/MoogsMissingVillages
modReleases=https://github.com/FinnSetchell/MoogsMissingVillages/releases
modIssues=https://github.com/FinnSetchell/MoogsMissingVillages/issues
modDiscord=https://discord.gg/S5nffJbuvA
modKofi=https://ko-fi.com/finndog
modCurseforge=https://www.curseforge.com/minecraft/mc-mods/mmv-moogs-missing-villages
modModrinth=https://modrinth.com/mod/mmv-moogs-missing-villages

structureLibVersionRange=[1.0.0,)

publishDisplayPrefix=MMV
publishDisplaySuffix=[UNIVERSAL]

modrinthProjectId=spZb29SD
curseforgeProjectId=1153951
curseforgeProjectSlug=mmv-moogs-missing-villages
modrinthProjectSlug=mmv-moogs-missing-villages
publishMcStart=1.20
publishMcEnd=1.20.6
releaseType=minor

discordAvatarUrl=https://media.forgecdn.net/avatars/thumbnails/1175/818/64/64/638748086115979970.webp
discordEmbedColor=#f7941f
discordThumbnailUrl=https://www.bisecthosting.com/images/CF/MMV_Moogs_Missing_Villages/MP_MMV_MoogsMissingVillages_header.webp
discordRoleId=1466012771379581039
discordPing=true