org.gradle.jvmargs=-Xmx2G
modName=MoogsMissingVillages
minecraftVersion=1.21
modVersion=2.0.0
modId=mmv

# Mod metadata
modDescription=This is a mod that adds in the missing jungle and swamp villages in a vanilla-friendly way and style
modHomepage=https://www.curseforge.com/minecraft/mc-mods/mmv-moogs-missing-villages
modSources=https://github.com/FinnSetchell/MoogsMissingVillages
modIssues=https://github.com/FinnSetchell/MoogsMissingVillages/issues
structureLibVersionRange=[1.0,)

# Publishing display customization
publishDisplayPrefix=MMV
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=spZb29SD
curseforgeProjectId=1153951
publishMcStart=1.21
publishMcEnd=1.21.10