modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/FinnSetchell/MoogsStructuresTemplate/issues" #optional
license="https://github.com/FinnSetchell/MoogsStructuresTemplate/blob/1.20-MultiLoader/LICENSE"

[[mods]]
    modId="mvs"
    logoFile= "assets/mst/icon.png"
    logoBlur=false
    version="${version}"
    displayName="Moog's Structures Template"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/moogs-structures"
    authors="FinnDog"
    credits="Thanks to the amazing builders as well as TelepathicGrunt for their structure mod template and rs"
    description='''
    Moogs Structures brings life, fun and variety to your Minecraft world!
    Explore awesome new structures made with vanilla blocks and entities, and discover loot,
    enemies, and villagers along the way. This mod is compatible with any modpack and keeps
    the vanilla feel of the game!
    '''

[[mixins]]
    config = "mst-neoforge.mixins.json"

[[mixins]]
    config = "mst-common.mixins.json"

[[dependencies.mvs]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"